name: uwgda2020
channels:
  - conda-forge
dependencies:
  - bokeh
  - cartopy
  - contextily
  - dask
  - dask-labextension
  - datashader
  - descartes
  - distributed
  - fiona
  - folium
  - fsspec
  - gcsfs
  - gdal
  - geojson
  - geopandas
  - geoviews
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyterlab
  - matplotlib
  - matplotlib-scalebar
  - nbgitpuller
  - numpy
  - pandas
  - panel
  - parallel
  - pillow
  - pip
  - pyproj
  - python
  - rasterio
  - rasterstats
  - rio-cogeo
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - tornado
  - xarray
  - zarr
